In [32]:
import numpy as np
np.array([1,2,3,4,5])

arr1d = np.array([1,2,3,4,5])
display(arr1d)

arr2d = np.array([[
        [1,2,3,],
        [4,5,6,]
]])

display(arr2d)

arr3d = np.array([
    [1,2,3],
    [1,2,3],
    [3,4,2]
])

display(arr3d, arr3d.dtype)

array = np.array([[1,2,3],[4,5,6]])
display(array.dtype)

array = np.array([[1,2,3],[4,5,6]], dtype=np.int64)
display(array.dtype)

array = np.array([[1,2,3],[4,5,6]], dtype = np.float32)
display(array.dtype)

array = np.array([[1,2,3],[4,5,6]],dtype=float)
display(array.dtype)

print(f"array.size : {array.size}")
print(f"array.shape : {array.shape}")
print(f"array.ndim : {array.ndim}")

zeros_array = np.zeros((3))
display(zeros_array)
print(f"zeros_array.ndim : {zeros_array.ndim}")

zeros_array = np.zeros((3,3))
display(zeros_array)
print(f"zeros_array.ndim : {zeros_array.ndim}")

zeros_array = np.zeros((3,3,3))
display(zeros_array)

array = np.ones((2,2,2))
display(array)

full_array = np.full((4,4),10)
display(full_array)

eye_array = np.eye(3)
display(eye_array)

array([1, 2, 3, 4, 5])

array([[[1, 2, 3],
        [4, 5, 6]]])

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 2]])

dtype('int32')

dtype('int32')

dtype('int64')

dtype('float32')

dtype('float64')

array.size : 6
array.shape : (2, 3)
array.ndim : 2


array([0., 0., 0.])

zeros_array.ndim : 1


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

zeros_array.ndim : 2


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
display(np.array(range(100)))

display(np.array(range(1,10,2)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([1, 3, 5, 7, 9])

## 인덱싱, 슬라이싱

In [47]:
arr1 = np.array([5,10,15,20,25])
display(arr1)
print(arr1[0])
print(arr1[1])
print(arr1[-1])
print(arr1[-2])

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
display(arr2)
display(arr2[0,1])
display(arr2[1])
display(arr2[:,2])

arr3 = np.array([
                [[1,2],[3,4],[5,6],[7,8]]
                  ])
display(arr3)
display(f"arr3.ndim : {arr3.ndim}")

arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
display(arr1[2:5])

arr2 = np.array([ [0,1,2], [3,4,5], [6,7,8] ])
display(arr2)
display(arr2[0:2, 0:2])
display(arr2[:2, :2])


arr3 = np.array([[ [0,1,2], [3,4,5], [6,7,8] ] ])
display(arr3)



array([ 5, 10, 15, 20, 25])

5
10
25
20


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2

array([4, 5, 6])

array([3, 6, 9])

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

'arr3.ndim : 3'

array([2, 3, 4])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1],
       [3, 4]])

array([[0, 1],
       [3, 4]])

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

## 기본 연산

In [69]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

display(arr1 + arr2)
display(arr1 - arr2)
display(arr1 * arr2)
display(arr1 ** arr2)
display(arr1 / arr2)
display(arr1 // arr2)
display(arr1 % arr2)

display(f"np.sum(arr1) : {np.sum(arr1)}")
display(f"arr1.sum() : {arr1.sum()}")

display(f"np.mean(arr1) : {np.mean(arr1)}")
display(f"arr1.mean() : {arr1.mean()}")

display(f"np.max(arr1) : {np.max(arr1)}")
display(f"arr1.max() : {arr1.max()}")

display(f"np.min(arr1) : {np.min(arr1)}")
display(f"arr1.min() : {arr1.min()}")

display(f"np.median(arr1) : {np.median(arr1)}")

display(f"np.std(arr1) : {np.std(arr1)}")
display(f"arr1.std() : {arr1.std()}")

display(f"np.var(arr1) : {np.var(arr1)}")
display(f"arr1.var() : {arr1.var()}")

display(f"np.sum([1,1,2,3,4,5]) : {np.sum([1,1,2,3,4,5])}")
display(f"np.array([1.1.2.3.4.5]).sum() : {np.array([1,1,2,3,4,5]).sum()}")

array([5, 7, 9])

array([-3, -3, -3])

array([ 4, 10, 18])

array([  1,  32, 729])

array([0.25, 0.4 , 0.5 ])

array([0, 0, 0])

array([1, 2, 3])

'np.sum(arr1) : 6'

'arr1.sum() : 6'

'np.mean(arr1) : 2.0'

'arr1.mean() : 2.0'

'np.max(arr1) : 3'

'arr1.max() : 3'

'np.min(arr1) : 1'

'arr1.min() : 1'

'np.median(arr1) : 2.0'

'np.std(arr1) : 0.816496580927726'

'arr1.std() : 0.816496580927726'

'np.var(arr1) : 0.6666666666666666'

'arr1.var() : 0.6666666666666666'

'np.sum([1,1,2,3,4,5]) : 16'

'np.array([1.1.2.3.4.5]).sum() : 16'

In [76]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
display(arr1)
display(f"np.sum(arr1) : {np.sum(arr1) }")
display(f"np.sum(arr1) : {np.sum(arr1, axis=1)}")
display(f"np.sum(arr1) : {np.sum(arr1, axis=0)}")

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

'np.sum(arr1) : 45'

'np.sum(arr1) : [ 6 15 24]'

'np.sum(arr1) : [12 15 18]'

In [79]:
a = np.array([1,2,3])
b = np.array([1,2,3])
display(a+b)

b = np.array([[10],
              [20],
              [30]])
display(a+b)

b = 5
display(a+b)

array([2, 4, 6])

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

array([6, 7, 8])

In [88]:
arr = np.array([1,4,9,16,25])
display(f"np.sqrt(arr) : {np.sqrt(arr)}")
display(f"np.exp(arr) : {np.exp(arr)}")
display(f"np.log(arr) : {np.log(arr)}")
display(f"np.power(arr,2), {np.power(arr,2)}")

a = np.array([1,2,3])
b = np.array([4,5,6])
display(f"np.add(a,b) : {np.add(a,b)}")
display(f"np.subtract(a,b) : {np.subtract(a,b)}")

'np.sqrt(arr) : [1. 2. 3. 4. 5.]'

'np.exp(arr) : [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06\n 7.20048993e+10]'

'np.log(arr) : [0.         1.38629436 2.19722458 2.77258872 3.21887582]'

'np.power(arr,2), [  1  16  81 256 625]'

'np.add(a,b) : [5 7 9]'

'np.subtract(a,b) : [-3 -3 -3]'